services:
  game:
    build:
      dockerfile: Dockerfile
      context: ./game/
    # command: ["emrun", "--no_browser", "--port", "8080", "."]
    ports:
      - "8080:8080"

  # web:
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./web/